in stead of random state in train_test_split you better go for folds if there are 100 samples let us take 20 in 1 fold then we have 5 folds .
for first time  use fold 1 for testing and fold(2 to 5) for training 
for second time use fold 2 for testing and fold 1,3,4,5 for training 
lly upto all
then individually calculate score and do an average of score give avg score as  output



In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [5]:
digits=load_digits()

In [6]:
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [7]:
x=digits['data']
x

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [9]:
y=digits.target
y

array([0, 1, 2, ..., 8, 9, 8])

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [25]:
lreg=LogisticRegression()
lreg.fit(x_train,y_train)
lreg.score(x_test,y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9629629629629629

In [26]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9925925925925926

In [27]:
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9814814814814815

In [70]:
from sklearn.model_selection import StratifiedKFold

In [71]:
sf=StratifiedKFold()

In [74]:
def get_score(model,x_train,x_test,y_train,y_test):
        model.fit(x_train,y_train)
        return model.score(x_test,y_test)



l,s,r=[],[],[]
for train_index,test_index in sf.split(x,y):
    x_train,x_test,y_train,y_test=x[train_index],x[test_index],y[train_index],y[test_index]
    l.append(get_score(LogisticRegression(max_iter=5000),x_train,x_test,y_train,y_test))
    s.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    r.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))
print(l)
print(s)
print(r)
      

[0.925, 0.8777777777777778, 0.9387186629526463, 0.9331476323119777, 0.8969359331476323]
[0.9611111111111111, 0.9444444444444444, 0.9832869080779945, 0.9888579387186629, 0.9387186629526463]
[0.9277777777777778, 0.9, 0.9665738161559888, 0.9610027855153204, 0.924791086350975]


by seeing above results mostly svm performs well

now why we need this much effort simply do cross_val_score(model,x,y) from model selection in sklearn


In [91]:
from sklearn.model_selection import cross_val_score

In [93]:
print(cross_val_score(LogisticRegression(),x,y))
print(cross_val_score(SVC(),x,y))
print(cross_val_score(RandomForestClassifier(n_estimators=500),x,y))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


[0.92222222 0.86944444 0.94150418 0.93871866 0.89693593]
[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
[0.93055556 0.925      0.9637883  0.96657382 0.92479109]


since we increase the estimators in random forest, svm is more accurate ,see we get to know  about this using the validation.