In [106]:
import numpy as np

In [107]:
a1=np.array(range(5))
a1

array([0, 1, 2, 3, 4])

In [108]:
a2=np.array([[1,2],[3,4,],[5,6]])
a2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [109]:
a2.ndim

2

In [110]:
a2.dtype

dtype('int64')

In [111]:
a=np.array([[1,2],[3,4,],[5,6]],dtype=np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [112]:
a.itemsize

8

In [113]:
np.arange(2,5)

array([2, 3, 4])

In [114]:
np.arange(4,9,2)

array([4, 6, 8])

In [115]:
np.linspace(1,5,10)  #generates 10 linear spaced numbers bwn 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [116]:
print(a)
print('================')
a=a.reshape(2,3)
print(a)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [117]:
a.reshape(6,1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

In [118]:
a.ravel()           #to flattern the data in 1d

array([1., 2., 3., 4., 5., 6.])

In [119]:
a.min()

1.0

In [120]:
a.max()

6.0

In [121]:
a.sum()

21.0

In [122]:
print(a)
a.sum(axis=0)

[[1. 2. 3.]
 [4. 5. 6.]]


array([5., 7., 9.])

In [123]:
print(a)
a.sum(axis=1)           #axis=1 is sweeps through vertically   >
                        #axis=0 is sweeps through horizontally ^

[[1. 2. 3.]
 [4. 5. 6.]]


array([ 6., 15.])

In [124]:
c=np.array([[1,2],[3,4]])
d=np.array([[2,3],[4,5]])
c.dot(d)

array([[10, 13],
       [22, 29]])

Numpy slicing

In [125]:
a=np.array([6,7,8])
a[1:]

array([7, 8])

In [126]:
a[-1]

8

In [127]:
b=np.array([[4,5,6],[1,2,3],[7,8,9]])
b[1,2]

3

In [128]:
b[1:]

array([[1, 2, 3],
       [7, 8, 9]])

In [129]:
b[1:,2]

array([3, 9])

In [130]:
b[:,0]

array([4, 1, 7])

In [131]:
b

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [132]:
b[1:,1]       # for getting y axis elements 2,8 need to slice x
              #from 1 and 2 rows slice 1st column

array([2, 8])

In [133]:
b[2,:2]      #for getting x axis elements 7,8 need to slice y
              #in 2 nd row slice first two columns

array([7, 8])

In [134]:
b[:,1:]       #b[x,y] x is row selection and y is column selection until what we want

array([[5, 6],
       [2, 3],
       [8, 9]])

In [135]:
for row in b:
     for ele in row:
        print(ele)

4
5
6
1
2
3
7
8
9


In [136]:
print(a)
print('==========')
print(b)
print('===========')
c=np.vstack((a,b))
print(c)

[6 7 8]
[[4 5 6]
 [1 2 3]
 [7 8 9]]
[[6 7 8]
 [4 5 6]
 [1 2 3]
 [7 8 9]]


In [137]:
d=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [138]:
np.hstack((c,d))

array([[ 6,  7,  8,  1,  2,  3],
       [ 4,  5,  6,  4,  5,  6],
       [ 1,  2,  3,  7,  8,  9],
       [ 7,  8,  9, 10, 11, 12]])

In [140]:
e=np.arange(30).reshape(2,15)
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [146]:
x,y,z=np.hsplit(e,3)
print(x)
print(y)
print(z)

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [147]:
i,j=np.vsplit(e,2)
print(i)
print(j)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


Indexing with boolean array

In [156]:
a=np.arange(12).reshape(3,4)
print(a)
b=a>4
b

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [157]:
print(a[b])
a[b]=-1
a

[ 5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

we have simply converted elements to -1 which are greater than 4


In [ ]:
#np.savetext("test.txt",a)  for saving a array
#np.loadtxt("test.txt")     for loading a txtfile